### ISSUE TITLE
doubling in certain tracks

### ISSUE THREAD

**Issue by jon-myers** [jon-myers/idtp#159]
there is a visual overlay of the transcription on top of itself. Has occurred in Dard's transcription of Hafiz Ali Khan Yaman. When this occurs, user is unable to save. 

console error:

`TypeError: Cannot read properties of null (reading 'ownerDocument')
    at new pt (transform-31f0ced6.js:1:5848)
    at Ie (transform-31f0ced6.js:1:6395)
    at v.qe [as data] (transform-31f0ced6.js:1:7164)
    at Proxy.codifiedAddPlucks (EditorComponent-cdd4b18a.js:187:70213)
    at Proxy.codifiedAddArticulations (EditorComponent-cdd4b18a.js:187:68915)
    at Proxy.codifiedAddTraj (EditorComponent-cdd4b18a.js:187:91829)
    at EditorComponent-cdd4b18a.js:187:91979
    at Proxy.forEach (<anonymous>)
    at EditorComponent-cdd4b18a.js:187:91951
    at Proxy.forEach (<anonymous>)
Ua @ index-116aa40f.js:1
transform-31f0ced6.js:1 Uncaught TypeError: Cannot read properties of null (reading 'ownerDocument')
    at new pt (transform-31f0ced6.js:1:5848)
    at Ie (transform-31f0ced6.js:1:6395)
    at v.qe [as data] (transform-31f0ced6.js:1:7164)
    at Proxy.codifiedAddPlucks (EditorComponent-cdd4b18a.js:187:70213)
    at Proxy.codifiedAddArticulations (EditorComponent-cdd4b18a.js:187:68915)
    at Proxy.codifiedAddTraj (EditorComponent-cdd4b18a.js:187:91829)
    at EditorComponent-cdd4b18a.js:187:91979
    at Proxy.forEach (<anonymous>)
    at EditorComponent-cdd4b18a.js:187:91951
    at Proxy.forEach (<anonymous>)
editor:1 The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
editor:1 The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_check.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_detection.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`

![IMG_4094](https://user-images.githubusercontent.com/6957461/225098870-4be001c8-75b5-46fd-a334-14e05ab51aa3.jpg)

**Comment by jon-myers** [comment]
I think this has been solved
